### ISSUE TITLE
Several questions about WebP generation

### ISSUE THREAD

**Issue by zhandosweb** [sverrirs/jekyll-webp#8]
Hello! 

Please, let me ask several questions about your plugin: 

1. All WebP images generated by the plugin will be stored in the same folder, where is the main .jpg image? 

2. If I optimize all my .jpg images using Photoshop. Should I off image optimization (serve) function of the plugin? 

And all generated WebP images will be less size, that original .jpg images, right? Because WebP newer and should be less size. than .jpg. 

Sorry sir for my bad English. Hello from Kazakhstan! And thank you for your work!

**Comment by johnpitchko** [comment]
> All WebP images generated by the plugin will be stored in the same folder, where is the main .jpg image?

Yes, sort of. They will be generated in the same directory as the source image, but only in the `_site` directory. So if you store your build images in `assets/images`, then the plugin will generate your images in `_site/assets/images`.

This confused me at first because after the plugin ran successfully, I couldn't find the images!
